/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ParseQRKt */

#ifndef _Included_ParseQRKt
#define _Included_ParseQRKt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ParseQRKt
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ParseQRKt_start
  (JNIEnv *, jclass);

/*
 * Class:     ParseQRKt
 * Method:    qrScan
 * Signature: (Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_ParseQRKt_qrScan
  (JNIEnv *, jclass, jobject, jint, jint, jobject);

/*
 * Class:     ParseQRKt
 * Method:    end
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ParseQRKt_end
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
